# Site Settings
title: "Shine & Shield Reviews"
description: "Professional boat and auto detailing product reviews and comparisons"
baseurl: "/shine-shield-reviews"
url: "https://landwehr72.github.io"
author: "Shine & Shield Reviews"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  reviews:
    output: true
    permalink: /reviews/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: /
  - title: Boat Reviews
    url: /boat-reviews/
  - title: Auto Reviews  
    url: /auto-reviews/
  - title: Best Products
    url: /best-products/
  - title: Buying Guides
    url: /guides/
  - title: About
    url: /about/

# Social
social:
  - platform: youtube
    url: "#"
  - platform: instagram
    url: "#"

# SEO
google_analytics: # Add your GA tracking ID later
